name: environment-workflow
on:
  pull_request:
    branches:
      - develop
      - prod
jobs:
  unit-test:
    name: unit-test
    runs-on: macos-latest
    steps:
      - name: Checking out to working branch...
        uses: actions/checkout@v4
      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - run: npm install
      - run: npm test

  python-test:
    name: test-endpoints
    runs-on: macos-latest
    needs: [ unit-test ]
    steps:
      - name: Checking out to working branch...
        uses: actions/checkout@v4
      - name: Setting up Python env...
        uses: actions/setup-python@v4
      - name: Installing dependencies...
        run: cd test/ && pip install -r requirements.txt
      - name: Running pytest framework and exporting test results...
        env:
          DRIVE_LAMBDA_URL: ${{ secrets.DRIVE_LAMBDA_URL }}
          SITE_WEBHOOK_URL: ${{ secrets.SITE_WEBHOOK_URL }}
        run: cd test && pytest -v --log-cli-level=DEBUG testEndpoints/*.py
