name: feature-test-development-workflow
on:
  push:
    branches:
      - feature/*
      - develop
jobs:

  lint:
    name: lint
    runs-on: macos-latest
    steps:
      - name: Checking out to working branch...
        uses: actions/checkout@v4
      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - run: npm i eslint-config-next
      - run: npm init @eslint/config
      - run: npx eslint ./

  test:
    name: test-endpoints
    runs-on: macos-latest
    steps:
      - name: Checking out to working branch...
        uses: actions/checkout@v4
      - name: Setting up Python env...
        uses : actions/setup-python@v4
      - name: Installing dependencies...
        run: cd test/ && pip install -r requirements.txt
      - name: Running pytest framework and exporting test results...
        run: pytest --log-cli-level=DEBUG -v testEndpoints/*.py
