name: feature-test-development-workflow
on:
  push:
    branches:
      - feature/*
jobs:

  lint:
    name: lint
    runs-on: macos-latest
    steps:
      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - run: npm init @eslint/config
      - run: npx eslint ./

